# A sample multi-node cluster config file
# A three node (two workers, one controller) cluster config
# To add more worker nodes, add another role: worker to the list
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mgmt
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6446
nodes:
- role: control-plane
  labels:
    tier: mgmt-cp
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"    
  extraPortMappings:
  - containerPort: 80
    hostPort: 83
    protocol: TCP
  - containerPort: 8080
    hostPort: 8083
    protocol: TCP
  - containerPort: 443
    hostPort: 446
    protocol: TCP